//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_KHACH_HANG
    {
        public int ID_KH { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public int SDT { get; set; }
        public int ID { get; set; }
    
        public virtual BANG_TAI_KHOAN_KHACH_HANG BANG_TAI_KHOAN_KHACH_HANG { get; set; }
    }
}
