//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SAN_PHAM
    {
        public int ID_CTSP { get; set; }
        public string Tensanpham { get; set; }
        public decimal Price { get; set; }
        public bool Trangthai { get; set; }
        public byte[] image { get; set; }
        public int Lienhe { get; set; }
        public string Mota { get; set; }
        public int ID_SP { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
