//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_VAN_CHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHA_VAN_CHUYEN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
            this.NHAN_VIEN_VAN_CHUYEN = new HashSet<NHAN_VIEN_VAN_CHUYEN>();
        }
    
        public int ID_NVC { get; set; }
        public string TenNVC { get; set; }
        public int SDT_NVC { get; set; }
        public string Email_NVC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAN_VIEN_VAN_CHUYEN> NHAN_VIEN_VAN_CHUYEN { get; set; }
    }
}
