//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN_VAN_CHUYEN
    {
        public int ID_NV { get; set; }
        public string Hoten { get; set; }
        public int SDT { get; set; }
        public int ID_NVC { get; set; }
    
        public virtual NHA_VAN_CHUYEN NHA_VAN_CHUYEN { get; set; }
    }
}
