//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
            this.CHI_TIET_SAN_PHAM = new HashSet<CHI_TIET_SAN_PHAM>();
        }
    
        public int ID_SP { get; set; }
        public int ID_NCC { get; set; }
        public int ID_LoaiSP { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public byte[] IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_SAN_PHAM> CHI_TIET_SAN_PHAM { get; set; }
        public virtual LOAI_SAN_PHAM LOAI_SAN_PHAM { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
